# Generated by Django 4.1 on 2022-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlsDatabase',
            fields=[
                ('url', models.TextField(max_length=10000, primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
